/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package program;
import java.util.Scanner;
import java.io.Console;

import org.json.simple.parser.ParseException;

public class App {
    
    public static void main(String[] args) throws ParseException {
        Console console = System.console();

        try (Scanner kb = new Scanner(System.in)) {
            System.out.print("Enter Username: ");
            String username = kb.nextLine();

            System.out.print("Enter Password: ");
            char[] passChars = console.readPassword();
            String password = new String(passChars);

            User user = UserManager.loadUser(username, password);

            if (user != null) {
                System.out.println("Welcome back, " + username + "!");
            } else {
                System.out.println("New user created: " + username);
                user = new User(username, password);
            }

            while (true) {
                System.out.println("\nMenu:");
                System.out.println("1. Add a new service");
                System.out.println("2. Get a service");
                System.out.println("3. Delete a service");
                System.out.println("4. Exit");

                int choice = kb.nextInt();
                kb.nextLine();
                switch (choice) {
                    case 1:
                        System.out.print("Enter service name: ");
                        String service = kb.nextLine();
                        System.out.print("Enter password for " + service + ": ");
                        char[] passwordChars = console.readPassword();
                        String pass = new String(passwordChars);
                        user.addPassword(service, pass);
                        break;
                    case 2:
                        System.out.print("Enter service name to get password: ");
                        String getService = kb.nextLine();
                        String retrievedPassword = user.getPassword(getService);
                        if (retrievedPassword != null) {
                            System.out.println("Password for " + getService + ": " + retrievedPassword);
                        } else {
                            System.out.println("Password not found for " + getService);
                        }
                        break;
                    case 3:
                        System.out.println("Enter service name to delte: ");
                        String deleteService = kb.nextLine();
                        user.deleteService(deleteService);
                        break;
                    default:
                        System.out.println("Invalid choice. Please try again.");
                    case 4:
                        // Save user data and exit
                        user.saveUserData();
                        System.out.println("Exiting. Goodbye!");
                        System.exit(0);
                }
            }
        }
    }
        
}

